version: '3'

vars:
  SHELL: pwsh

tasks:
  default:
    desc: Build the addon
    cmds:
      - task: build

  copy:
    desc: Copy sources files to scratchpad directory
    platforms: [windows]
    vars:
      SOURCE: addon\globalPlugins\voicemeeter
      DEST: ${env:appdata}\nvda\scratchpad\globalPlugins\voicemeeter\
    cmds:
      - "{{.SHELL}} -Command 'robocopy {{.SOURCE}} {{.DEST}} /NDL'"
    ignore_error: true

  build:
    desc: Build the addon
    platforms: [windows]
    cmds:
      - '{{.SHELL}} -Command "pdm run scons"'

  bump:
    desc: Bump the version number
    preconditions:
      - sh: '{{.SHELL}} -c "if (Get-Command bump) { exit 0 } else { exit 1 }"'
        msg: "The 'bump' command is not available. Run `go install github.com/onyx-and-iris/bump/cmd/bump@latest`."
    cmds:
      - |
        {{if eq .CLI_ARGS "show"}}
          {{.SHELL}} -c "bump show -f buildVars.py -p \"'addon_version': '(\d+\.\d+\.\d+)'\""
          {{.SHELL}} -c "bump show -f pyproject.toml -p \"version = .(\d+\.\d+\.\d+).\""
        {{else}}
          {{.SHELL}} -c "bump {{.CLI_ARGS}} -w -f buildVars.py -p \"'addon_version': '(\d+\.\d+\.\d+)'\""
          {{.SHELL}} -c "bump {{.CLI_ARGS}} -w -f pyproject.toml -p \"version = .(\d+\.\d+\.\d+).\""
        {{end}}
