version: '3'

vars:
  SHELL: pwsh

tasks:
  default:
    desc: Build the addon
    cmds:
      - task: build

  copy:
    desc: Copy sources files to scratchpad directory
    platforms: [windows]
    vars:
      SOURCE: addon\globalPlugins\voicemeeter
      DEST: ${env:appdata}\nvda\scratchpad\globalPlugins\voicemeeter\
    cmds:
      - "{{.SHELL}} -Command 'robocopy {{.SOURCE}} {{.DEST}} /NDL'"
    ignore_error: true

  build:
    desc: Build the addon
    platforms: [windows]
    cmds:
      - '{{.SHELL}} -Command "pdm run scons"'
